### ISSUE TITLE
Baud rate limitation and future features

### ISSUE THREAD

**Issue by mrv96** [PhilipMur/Serial-Comm-Tester#1]
Hi, i'm working with an high baud rate UART device (921600 ) so i modified your code in order to support my speed. In the future you could extend your baudrate selection to 921600 for example. An additional intresting feature could be a script executor. In my current project i send 32bit integers with 4 RS232 byte and now i need to save data received in HEX and then with another program i'm able to recover from hex my 32 bit integers. If you develop a live script executor on data reception i could get directly my integer numbers, and see them immediatly and at run time. Mine was only an example. It's not easy, i know, but your program could be the first with this feature.

**Comment by PhilipMur** [comment]
Hi mrv96,

The Baud Rate combobox will take any value you type in to it as well as the drop-down list , I made it this way for your that reason you explained.

I'm sorry i don't full understand what you task you are trying to carry out.

You can send/receive in real-time and send in HEX / Decimal and text based ,
It can also send from a file as well as save to file automatically or when you choose to save.
Is that what you are looking for ?

If not give me a good description of your task and i will look to implement it when i find more time.

Thanks for your interest in the project.
Philip M

**Comment by mrv96** [comment]
Sorry for the comboBox, i made a mistake.

For my task:
each ms I have to send with an Arduino to PC this pattern:

byte,Int32,Int32,Int32,Int32,Int32,Int32,Int32,Int32,byte,byte,byte,byte,byte,byte,byte,byte\n

If i send the line as a string, my line could be composed by a maximum of 3+10 * 8+3 * 8 + 17 = 129 byte of text, it means 1032000bps which is a very high value to manage with a microcontroller. In order to reduce the bps i send each byte of each number and then i shift the byte to recover my Int32 values (Int32 = byte + byte<<8+ byte<<16 + byte<<24) and add separator characters off-line, reducing required speed to (1+4 * 8+1 * 8) * 1000 * 8 = 328000bps. If i could make this shift operation in real-time, i could see immediatly and in real-time my data.

This is my example, but if you make an on received script executor you could help all people with this kind of problems (that are very common in electronic sector), or people that simply want to make a little computation of the data immediatly when they're received for whatever reason.

**Comment by PhilipMur** [comment]
I understand, a reply script for certain messages.

I will also look to adding a filter too for received messages in the
future.

Good idea I will implement it when I find more time as I'm very busy these
days.

Philip M

**Comment by PhilipMur** [comment]
Better late than never, i added the feature of a reply script aka automatic reply feature.

Philip M
