### ISSUE TITLE
not work for windows 10 ?

### ISSUE THREAD

**Issue by Wa-JHH** [PhilipMur/Serial-Comm-Tester#2]
windows 10 can not refresh com port?

**Comment by PhilipMur** [comment]
Hello bd7jhh,

Not sure what you mean as you provided no information with the issue but did you press the button named (Refresh COM ports).
I have windows 7,8.1,10 and all is working as it should be.

Philip M

**Comment by PhilipMur** [comment]
I'm guessing they found the refresh button.
