### ISSUE TITLE
can't receive data 

### ISSUE THREAD

**Issue by rajputyo** [PhilipMur/Serial-Comm-Tester#3]
hi philip 
thanks for this awesome software , i cant receive data but i can send it , i am using 1734-485ASC module , send data is perfectly fine and i can see the data at PLC software but somehow receiving is an issue , what end delimiters do use or handshaking mode?
master / slave ? or immediate ? how can i receive data from the module . i set end delimiters as $R$L or +CR +LF nothings seems to work .

plz help me with this

**Comment by PhilipMur** [comment]
You will have to check out the manufacturer  protocol to check what bytes the PLC is expecting .

Example :(STX/Class/Instance/Attribute/CRC8 =0x01/0x01/0x01/0x01/6F) and if it needs a checksum at the end to verify the data CRC or some sort of delimiter, use the checksum calc function in this project to see if the CRC is needed etc.

Check your wiring as well to make sure you don't have dodgy hardware/wiring, to check the cable i normally join TX and RX together at the end and the data i send is the data i should receive back.

To be honest if you don't have the protocol it will be very hard to do.

Also industrial hardware normally runs RS485 or RS422 network, not RS232 so i think you might need to get a RS485 to RS232 converter for you PC if you have not do so already.

Philip

**Comment by PhilipMur** [comment]
I presume what i said previously helped you out in your quest.

Philip M

**Comment by rajputyo** [comment]
Yes sir i changed the controller and used the checksum calculator and wired
the ground cable and it worked thanks a lot
