### ISSUE TITLE
Monitor  serial port inused

### ISSUE THREAD

**Issue by JohnnyZhang0628** [PhilipMur/Serial-Comm-Tester#4]
Hello,I'm a .net coder from china ,I want to create a project to monitor opening serial port .The project can do it?thanks

**Comment by PhilipMur** [comment]
Hello  JohnnyZhang0628 ,

Sorry for the late reply, 

To monitor the opening of a serial port it would be best to just make a call to WIN API32 and query that or use this program to try open a serial port and if it fails it means it is in use etc...

If its to monitor /sniff packets from another comport that is in use already then the answer is no maybe use a windows program like Portmon for Windows.

Philip
